Fix rbenv -> phpenv

diff --git a/libexec/phpenv-which b/libexec/phpenv-which
--- a/libexec/phpenv-which
+++ b/libexec/phpenv-which
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
 set -e
-[ -n "$RBENV_DEBUG" ] && set -x
+[ -n "$PHPENV_DEBUG" ] && set -x
 
-# Provide rbenv completions
+# Provide phpenv completions
 if [ "$1" = "--complete" ]; then
-  exec rbenv shims --short
+  exec phpenv shims --short
 fi
 
 expand_path() {
@@ -37,34 +37,34 @@ remove_from_path() {
   echo "${result%:}"
 }
 
-RBENV_VERSION="$(rbenv-version-name)"
-RBENV_COMMAND="$1"
+PHPENV_VERSION="$(phpenv-version-name)"
+PHPENV_COMMAND="$1"
 
-if [ -z "$RBENV_COMMAND" ]; then
-  echo "usage: rbenv which COMMAND" >&2
+if [ -z "$PHPENV_COMMAND" ]; then
+  echo "usage: phpenv which COMMAND" >&2
   exit 1
 fi
 
-if [ "$RBENV_VERSION" = "system" ]; then
-  PATH="$(remove_from_path "${RBENV_ROOT}/shims")"
-  RBENV_COMMAND_PATH="$(command -v "$RBENV_COMMAND")"
+if [ "$PHPENV_VERSION" = "system" ]; then
+  PATH="$(remove_from_path "${PHPENV_ROOT}/shims")"
+  PHPENV_COMMAND_PATH="$(command -v "$PHPENV_COMMAND")"
 else
-  RBENV_COMMAND_PATH="${RBENV_ROOT}/versions/${RBENV_VERSION}/bin/${RBENV_COMMAND}"
+  PHPENV_COMMAND_PATH="${PHPENV_ROOT}/versions/${PHPENV_VERSION}/bin/${PHPENV_COMMAND}"
 fi
 
-for script in $(rbenv-hooks which); do
+for script in $(phpenv-hooks which); do
   source "$script"
 done
 
-if [ -x "$RBENV_COMMAND_PATH" ]; then
-  echo "$RBENV_COMMAND_PATH"
+if [ -x "$PHPENV_COMMAND_PATH" ]; then
+  echo "$PHPENV_COMMAND_PATH"
 else
-  echo "rbenv: $RBENV_COMMAND: command not found" >&2
+  echo "phpenv: $PHPENV_COMMAND: command not found" >&2
 
-  versions="$(rbenv-whence "$RBENV_COMMAND" || true)"
+  versions="$(phpenv-whence "$PHPENV_COMMAND" || true)"
   if [ -n "$versions" ]; then
     { echo
-      echo "The \`$1' command exists in these Ruby versions:"
+      echo "The \`$1' command exists in these PHP versions:"
       echo "$versions" | sed 's/^/  /g'
       echo
     } >&2
