Fix rbenv -> phpenv

diff --git a/libexec/phpenv b/libexec/phpenv
--- a/libexec/phpenv
+++ b/libexec/phpenv
@@ -3,30 +3,30 @@ set -e
 export -n CDPATH
 
 if [ "$1" = "--debug" ]; then
-  export RBENV_DEBUG=1
+  export PHPENV_DEBUG=1
   shift
 fi
 
-if [ -n "$RBENV_DEBUG" ]; then
+if [ -n "$PHPENV_DEBUG" ]; then
   export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
   set -x
 fi
 
 abort() {
   { if [ "$#" -eq 0 ]; then cat -
-    else echo "rbenv: $*"
+    else echo "phpenv: $*"
     fi
   } >&2
   exit 1
 }
 
-if enable -f "${BASH_SOURCE%/*}"/../libexec/rbenv-realpath.dylib realpath 2>/dev/null; then
+if enable -f "${BASH_SOURCE%/*}"/../libexec/phpenv-realpath.dylib realpath 2>/dev/null; then
   abs_dirname() {
     local path="$(realpath "$1")"
     echo "${path%/*}"
   }
 else
-  [ -z "$RBENV_NATIVE_EXT" ] || abort "failed to load \`realpath' builtin"
+  [ -z "$PHPENV_NATIVE_EXT" ] || abort "failed to load \`realpath' builtin"
 
   READLINK=$(type -p greadlink readlink | head -1)
   [ -n "$READLINK" ] || abort "cannot find readlink - are you missing GNU coreutils?"
@@ -50,42 +50,42 @@ else
   }
 fi
 
-if [ -z "${RBENV_ROOT}" ]; then
-  RBENV_ROOT="${HOME}/.rbenv"
+if [ -z "${PHPENV_ROOT}" ]; then
+  PHPENV_ROOT="${HOME}/.phpenv"
 else
-  RBENV_ROOT="${RBENV_ROOT%/}"
+  PHPENV_ROOT="${PHPENV_ROOT%/}"
 fi
-export RBENV_ROOT
+export PHPENV_ROOT
 
-if [ -z "${RBENV_DIR}" ]; then
-  RBENV_DIR="$PWD"
+if [ -z "${PHPENV_DIR}" ]; then
+  PHPENV_DIR="$PWD"
 else
-  cd "$RBENV_DIR" 2>/dev/null || abort "cannot change working directory to \`$RBENV_DIR'"
-  RBENV_DIR="$PWD"
+  cd "$PHPENV_DIR" 2>/dev/null || abort "cannot change working directory to \`$PHPENV_DIR'"
+  PHPENV_DIR="$PWD"
   cd "$OLDPWD"
 fi
-export RBENV_DIR
+export PHPENV_DIR
 
 
 shopt -s nullglob
 
 bin_path="$(abs_dirname "$0")"
-for plugin_bin in "${RBENV_ROOT}/plugins/"*/bin; do
+for plugin_bin in "${PHPENV_ROOT}/plugins/"*/bin; do
   PATH="${plugin_bin}:${PATH}"
 done
 export PATH="${bin_path}:${PATH}"
 
-RBENV_HOOK_PATH="${RBENV_HOOK_PATH}:${RBENV_ROOT}/rbenv.d"
-if [ "${bin_path%/*}" != "$RBENV_ROOT" ]; then
-  # Add rbenv's own `rbenv.d` unless rbenv was cloned to RBENV_ROOT
-  RBENV_HOOK_PATH="${RBENV_HOOK_PATH}:${bin_path%/*}/rbenv.d"
+PHPENV_HOOK_PATH="${PHPENV_HOOK_PATH}:${PHPENV_ROOT}/phpenv.d"
+if [ "${bin_path%/*}" != "$PHPENV_ROOT" ]; then
+  # Add phpenv's own `phpenv.d` unless phpenv was cloned to PHPENV_ROOT
+  PHPENV_HOOK_PATH="${PHPENV_HOOK_PATH}:${bin_path%/*}/phpenv.d"
 fi
-RBENV_HOOK_PATH="${RBENV_HOOK_PATH}:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks"
-for plugin_hook in "${RBENV_ROOT}/plugins/"*/etc/rbenv.d; do
-  RBENV_HOOK_PATH="${RBENV_HOOK_PATH}:${plugin_hook}"
+PHPENV_HOOK_PATH="${PHPENV_HOOK_PATH}:/usr/local/etc/phpenv.d:/etc/phpenv.d:/usr/lib/phpenv/hooks"
+for plugin_hook in "${PHPENV_ROOT}/plugins/"*/etc/phpenv.d; do
+  PHPENV_HOOK_PATH="${PHPENV_HOOK_PATH}:${plugin_hook}"
 done
-RBENV_HOOK_PATH="${RBENV_HOOK_PATH#:}"
-export RBENV_HOOK_PATH
+PHPENV_HOOK_PATH="${PHPENV_HOOK_PATH#:}"
+export PHPENV_HOOK_PATH
 
 shopt -u nullglob
 
@@ -93,23 +93,23 @@ shopt -u nullglob
 command="$1"
 case "$command" in
 "" )
-  { rbenv---version
-    rbenv-help
+  { phpenv---version
+    phpenv-help
   } | abort
   ;;
 -v | --version )
-  exec rbenv---version
+  exec phpenv---version
   ;;
 -h | --help )
-  exec rbenv-help
+  exec phpenv-help
   ;;
 * )
-  command_path="$(command -v "rbenv-$command" || true)"
+  command_path="$(command -v "phpenv-$command" || true)"
   [ -n "$command_path" ] || abort "no such command \`$command'"
 
   shift 1
   if [ "$1" = --help ]; then
-    exec rbenv-help "$command"
+    exec phpenv-help "$command"
   else
     exec "$command_path" "$@"
   fi
